-- Z Control - Transporte: cambios urgentes 2026-05-13
-- Ejecutar en Supabase SQL Editor antes de usar duración de ruta,
-- edición de viajes no timbrados y facturación del servicio.

ALTER TABLE public.tr_rutas
  ADD COLUMN IF NOT EXISTS duracion_estimada_min integer NOT NULL DEFAULT 0;

ALTER TABLE public.tr_viajes
  ADD COLUMN IF NOT EXISTS duracion_estimada_min integer NOT NULL DEFAULT 0;

ALTER TABLE public.tr_viajes
  DROP CONSTRAINT IF EXISTS tr_viajes_status_check;

ALTER TABLE public.tr_viajes
  ADD CONSTRAINT tr_viajes_status_check CHECK (
    status IN ('borrador', 'programado', 'en_ruta', 'timbrado', 'cancelado', 'error')
  );

CREATE TABLE IF NOT EXISTS public.tr_facturas_servicio (
  id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            text        NOT NULL,
  cliente_id         bigint      REFERENCES public.tr_clientes(id) ON DELETE SET NULL,
  viaje_ids          jsonb       NOT NULL DEFAULT '[]'::jsonb,
  cfdi_relacionados  jsonb       NOT NULL DEFAULT '[]'::jsonb,
  rfc_receptor       text        NOT NULL DEFAULT '',
  nombre_receptor    text        NOT NULL DEFAULT '',
  cp_receptor        text        NOT NULL DEFAULT '',
  regimen_fiscal     text        NOT NULL DEFAULT '601',
  uso_cfdi           text        NOT NULL DEFAULT 'G03',
  concepto           text        NOT NULL DEFAULT 'Servicio de transporte de hidrocarburos',
  subtotal           numeric     NOT NULL DEFAULT 0,
  iva                numeric     NOT NULL DEFAULT 0,
  total              numeric     NOT NULL DEFAULT 0,
  forma_pago         text        NOT NULL DEFAULT '99',
  metodo_pago        text        NOT NULL DEFAULT 'PPD',
  moneda             text        NOT NULL DEFAULT 'MXN',
  uuid_sat           text        NOT NULL DEFAULT '',
  xml_content        text        NOT NULL DEFAULT '',
  pdf_url            text        NOT NULL DEFAULT '',
  status             text        NOT NULL DEFAULT 'preparada',
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tr_facturas_servicio_status_check CHECK (
    status IN ('preparada', 'timbrada', 'cancelada', 'error')
  )
);

CREATE INDEX IF NOT EXISTS idx_tr_facturas_servicio_user_id
  ON public.tr_facturas_servicio (user_id);

CREATE INDEX IF NOT EXISTS idx_tr_facturas_servicio_created_at
  ON public.tr_facturas_servicio (created_at);

ALTER TABLE public.tr_facturas_servicio ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tr_facturas_servicio_user_policy
  ON public.tr_facturas_servicio;

CREATE POLICY tr_facturas_servicio_user_policy
  ON public.tr_facturas_servicio
  FOR ALL
  USING (user_id = auth.uid()::text);
