-- Transporte v2: cancelaciones y cierre mensual de Control Volumetrico.
-- No modifica el modulo Gas LP.

alter table if exists public.tr_cfdi
  add column if not exists cancelacion_status text,
  add column if not exists cancelacion_motivo text,
  add column if not exists cancelacion_uuid_sustitucion text,
  add column if not exists cancelacion_resultado jsonb not null default '{}'::jsonb,
  add column if not exists canceled_at timestamptz,
  add column if not exists canceled_by text;

alter table if exists public.tr_facturas_servicio
  add column if not exists cancelacion_status text,
  add column if not exists cancelacion_motivo text,
  add column if not exists cancelacion_uuid_sustitucion text,
  add column if not exists cancelacion_resultado jsonb not null default '{}'::jsonb,
  add column if not exists canceled_at timestamptz,
  add column if not exists canceled_by text;

create table if not exists public.tr_covol_month_closures (
  id                 bigint generated by default as identity primary key,
  user_id            text not null,
  perfil_id          bigint not null,
  periodo            text not null check (periodo ~ '^[0-9]{4}-[0-9]{2}$'),
  num_permiso_cne    text not null,
  clave_instalacion  text not null default '',
  tipo_reporte       text not null default 'TRA',
  status             text not null default 'cerrado',
  metadata           jsonb not null default '{}'::jsonb,
  closed_at          timestamptz not null default now(),
  closed_by          text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint tr_covol_month_closures_unique
    unique (user_id, perfil_id, periodo, num_permiso_cne)
);

create index if not exists idx_tr_covol_month_closures_user_periodo
  on public.tr_covol_month_closures (user_id, perfil_id, periodo);

create index if not exists idx_tr_cfdi_cancel_status
  on public.tr_cfdi (user_id, perfil_id, tipo_cfdi, status);

create index if not exists idx_tr_facturas_servicio_status_periodo
  on public.tr_facturas_servicio (user_id, perfil_id, status, created_at);

alter table public.tr_covol_month_closures enable row level security;

drop policy if exists tr_covol_month_closures_user_policy
  on public.tr_covol_month_closures;

create policy tr_covol_month_closures_user_policy
  on public.tr_covol_month_closures
  for all
  using (user_id = auth.uid()::text)
  with check (user_id = auth.uid()::text);
