-- GE CONTROL - Transporte fiscal-operativo fase 1
-- Staging-safe: agrega catálogos y defaults fiscales sin borrar datos.

alter table if exists public.tr_clientes
  add column if not exists metodo_pago_default text not null default 'PUE',
  add column if not exists forma_pago_default text not null default '03',
  add column if not exists iva_tasa_default numeric not null default 0.16,
  add column if not exists retencion_tasa_default numeric not null default 0,
  add column if not exists aplica_iva_default boolean not null default true,
  add column if not exists aplica_retencion_default boolean not null default false,
  add column if not exists reglas_fiscales jsonb not null default '{}'::jsonb,
  add column if not exists observaciones_fiscales text not null default '';

create table if not exists public.tr_origenes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  nombre text not null,
  rfc text not null default '',
  cp text not null default '',
  direccion text not null default '',
  tipo text not null default 'terminal',
  permiso_operacion_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_destinos (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  cliente_id bigint references public.tr_clientes(id) on delete set null,
  nombre text not null,
  rfc text not null default '',
  cp text not null default '',
  direccion text not null default '',
  tipo text not null default 'cliente',
  metadata jsonb not null default '{}'::jsonb,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_centros_emisores (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  nombre text not null,
  rfc text not null default '',
  cp text not null default '',
  regimen_fiscal text not null default '',
  serie_cfdi text not null default 'TR',
  serie_factura_servicio text not null default 'FS',
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_remolques (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  placas text not null,
  subtipo_rem text not null default '',
  capacidad_litros numeric not null default 0,
  aseguradora text not null default '',
  poliza_seguro text not null default '',
  poliza_medio_ambiente text not null default '',
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_vehiculo_remolques (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  vehiculo_id bigint not null references public.tr_vehiculos(id) on delete cascade,
  remolque_id bigint not null references public.tr_remolques(id) on delete cascade,
  frecuente boolean not null default true,
  orden integer not null default 1,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, vehiculo_id, remolque_id)
);

create table if not exists public.tr_vehiculo_seguros (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  vehiculo_id bigint references public.tr_vehiculos(id) on delete cascade,
  remolque_id bigint references public.tr_remolques(id) on delete cascade,
  tipo text not null default 'responsabilidad_civil',
  aseguradora text not null default '',
  poliza text not null default '',
  vigencia_desde date,
  vigencia_hasta date,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_permisos_operacion (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  tipo_permiso text not null default 'CNE',
  numero_permiso text not null,
  autoridad text not null default 'CNE',
  producto text not null default '',
  modalidad text not null default '',
  titular_rfc text not null default '',
  vigencia_desde date,
  vigencia_hasta date,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_vehiculo_permisos (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  vehiculo_id bigint references public.tr_vehiculos(id) on delete cascade,
  permiso_id bigint not null references public.tr_permisos_operacion(id) on delete cascade,
  producto text not null default '',
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, vehiculo_id, permiso_id, producto)
);

-- Compatibilidad con staging: si alguna tabla ya existia por una migracion
-- parcial/legacy, CREATE TABLE IF NOT EXISTS no agrega columnas nuevas.
alter table if exists public.tr_origenes
  add column if not exists rfc text not null default '',
  add column if not exists cp text not null default '',
  add column if not exists direccion text not null default '',
  add column if not exists tipo text not null default 'terminal',
  add column if not exists permiso_operacion_id bigint,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists activo boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_destinos
  add column if not exists cliente_id bigint,
  add column if not exists rfc text not null default '',
  add column if not exists cp text not null default '',
  add column if not exists direccion text not null default '',
  add column if not exists tipo text not null default 'cliente',
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists activo boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_centros_emisores
  add column if not exists rfc text not null default '',
  add column if not exists cp text not null default '',
  add column if not exists regimen_fiscal text not null default '',
  add column if not exists serie_cfdi text not null default 'TR',
  add column if not exists serie_factura_servicio text not null default 'FS',
  add column if not exists activo boolean not null default true,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_remolques
  add column if not exists subtipo_rem text not null default '',
  add column if not exists capacidad_litros numeric not null default 0,
  add column if not exists aseguradora text not null default '',
  add column if not exists poliza_seguro text not null default '',
  add column if not exists poliza_medio_ambiente text not null default '',
  add column if not exists activo boolean not null default true,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_vehiculo_remolques
  add column if not exists frecuente boolean not null default true,
  add column if not exists orden integer not null default 1,
  add column if not exists activo boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_vehiculo_seguros
  add column if not exists remolque_id bigint,
  add column if not exists tipo text not null default 'responsabilidad_civil',
  add column if not exists aseguradora text not null default '',
  add column if not exists poliza text not null default '',
  add column if not exists vigencia_desde date,
  add column if not exists vigencia_hasta date,
  add column if not exists activo boolean not null default true,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_permisos_operacion
  add column if not exists tipo_permiso text not null default 'CNE',
  add column if not exists autoridad text not null default 'CNE',
  add column if not exists producto text not null default '',
  add column if not exists modalidad text not null default '',
  add column if not exists titular_rfc text not null default '',
  add column if not exists vigencia_desde date,
  add column if not exists vigencia_hasta date,
  add column if not exists activo boolean not null default true,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.tr_vehiculo_permisos
  add column if not exists producto text not null default '',
  add column if not exists activo boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_tr_origenes_user_perfil on public.tr_origenes(user_id, perfil_id, activo);
create index if not exists idx_tr_destinos_user_perfil on public.tr_destinos(user_id, perfil_id, cliente_id, activo);
create index if not exists idx_tr_centros_user_perfil on public.tr_centros_emisores(user_id, perfil_id, activo);
create index if not exists idx_tr_remolques_user_perfil on public.tr_remolques(user_id, perfil_id, activo);
create index if not exists idx_tr_permisos_user_perfil on public.tr_permisos_operacion(user_id, perfil_id, activo);

alter table if exists public.tr_vehiculo_remolques add column if not exists updated_at timestamptz not null default now();
alter table if exists public.tr_vehiculo_seguros add column if not exists updated_at timestamptz not null default now();
alter table if exists public.tr_vehiculo_permisos add column if not exists updated_at timestamptz not null default now();

alter table public.tr_origenes enable row level security;
alter table public.tr_destinos enable row level security;
alter table public.tr_centros_emisores enable row level security;
alter table public.tr_remolques enable row level security;
alter table public.tr_vehiculo_remolques enable row level security;
alter table public.tr_vehiculo_seguros enable row level security;
alter table public.tr_permisos_operacion enable row level security;
alter table public.tr_vehiculo_permisos enable row level security;

drop policy if exists tr_origenes_user_policy on public.tr_origenes;
create policy tr_origenes_user_policy on public.tr_origenes for all using (user_id = auth.uid()::text);
drop policy if exists tr_destinos_user_policy on public.tr_destinos;
create policy tr_destinos_user_policy on public.tr_destinos for all using (user_id = auth.uid()::text);
drop policy if exists tr_centros_user_policy on public.tr_centros_emisores;
create policy tr_centros_user_policy on public.tr_centros_emisores for all using (user_id = auth.uid()::text);
drop policy if exists tr_remolques_user_policy on public.tr_remolques;
create policy tr_remolques_user_policy on public.tr_remolques for all using (user_id = auth.uid()::text);
drop policy if exists tr_vehiculo_remolques_user_policy on public.tr_vehiculo_remolques;
create policy tr_vehiculo_remolques_user_policy on public.tr_vehiculo_remolques for all using (user_id = auth.uid()::text);
drop policy if exists tr_vehiculo_seguros_user_policy on public.tr_vehiculo_seguros;
create policy tr_vehiculo_seguros_user_policy on public.tr_vehiculo_seguros for all using (user_id = auth.uid()::text);
drop policy if exists tr_permisos_user_policy on public.tr_permisos_operacion;
create policy tr_permisos_user_policy on public.tr_permisos_operacion for all using (user_id = auth.uid()::text);
drop policy if exists tr_vehiculo_permisos_user_policy on public.tr_vehiculo_permisos;
create policy tr_vehiculo_permisos_user_policy on public.tr_vehiculo_permisos for all using (user_id = auth.uid()::text);
