-- GE CONTROL - Transporte operativo 2026-05-14
-- Extension aditiva del modulo Transporte. No reemplaza el flujo fiscal actual.
-- Ejecutar despues de:
--   transporte_urgentes_20260513.sql
--   zcontrol_multimodulo_facturacion_20260513.sql
--   transporte_multiempresa_20260513.sql

alter table if exists public.tr_viajes
  add column if not exists operacion_status text not null default 'programado',
  add column if not exists carta_porte_status text not null default 'pendiente',
  add column if not exists factura_status text not null default 'pendiente',
  add column if not exists liquidacion_status text not null default 'pendiente',
  add column if not exists documentos_status text not null default 'pendiente',
  add column if not exists tarifa_total numeric not null default 0,
  add column if not exists retencion numeric not null default 0,
  add column if not exists total_operativo numeric not null default 0,
  add column if not exists fecha_entrega_confirmada timestamptz,
  add column if not exists closed_at timestamptz;

alter table if exists public.tr_facturas_servicio_cartas
  add column if not exists perfil_id bigint;

create table if not exists public.tr_viaje_eventos (
  id            bigint generated by default as identity primary key,
  user_id       text not null,
  perfil_id     bigint,
  viaje_id      bigint not null references public.tr_viajes(id) on delete cascade,
  event_type    text not null,
  title         text not null default '',
  description   text not null default '',
  actor_type    text not null default 'system',
  actor_id      text not null default '',
  metadata      jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists idx_tr_eventos_user_perfil_viaje
  on public.tr_viaje_eventos(user_id, perfil_id, viaje_id, created_at desc);

create table if not exists public.tr_viaje_documentos (
  id            bigint generated by default as identity primary key,
  user_id       text not null,
  perfil_id     bigint,
  viaje_id      bigint not null references public.tr_viajes(id) on delete cascade,
  tipo          text not null,
  nombre        text not null default '',
  storage_bucket text not null default 'transport-documents',
  storage_path  text not null default '',
  mime_type     text not null default '',
  size_bytes    bigint not null default 0,
  uuid_sat      text not null default '',
  status        text not null default 'vigente',
  metadata      jsonb not null default '{}'::jsonb,
  created_by    text not null default '',
  created_at    timestamptz not null default now(),
  constraint tr_viaje_documentos_status_check check (status in ('vigente','reemplazado','cancelado','error'))
);

create index if not exists idx_tr_documentos_user_perfil_viaje
  on public.tr_viaje_documentos(user_id, perfil_id, viaje_id, created_at desc);

create table if not exists public.tr_tarifas (
  id              bigint generated by default as identity primary key,
  user_id         text not null,
  perfil_id       bigint,
  cliente_id      bigint references public.tr_clientes(id) on delete set null,
  ruta_id         bigint references public.tr_rutas(id) on delete set null,
  origen          text not null default '',
  destino         text not null default '',
  producto        text not null default '',
  regla_calculo   text not null default 'litros',
  tarifa          numeric not null default 0,
  iva_tasa        numeric not null default 0.16,
  retencion_tasa  numeric not null default 0.04,
  aplica_iva      boolean not null default true,
  aplica_retencion boolean not null default true,
  moneda          text not null default 'MXN',
  vigencia_desde  date,
  vigencia_hasta  date,
  prioridad       integer not null default 100,
  activo          boolean not null default true,
  metadata        jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint tr_tarifas_regla_check check (regla_calculo in ('litros','kilos','viaje','distancia','manual'))
);

create index if not exists idx_tr_tarifas_lookup
  on public.tr_tarifas(user_id, perfil_id, cliente_id, ruta_id, activo, prioridad);

create table if not exists public.tr_gastos_viaje (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  perfil_id   bigint,
  viaje_id    bigint not null references public.tr_viajes(id) on delete cascade,
  chofer_id   bigint references public.tr_choferes(id) on delete set null,
  tipo        text not null default 'otro',
  descripcion text not null default '',
  importe     numeric not null default 0,
  moneda      text not null default 'MXN',
  status      text not null default 'pendiente',
  documento_id bigint references public.tr_viaje_documentos(id) on delete set null,
  created_at  timestamptz not null default now(),
  constraint tr_gastos_status_check check (status in ('pendiente','aprobado','rechazado','pagado'))
);

create index if not exists idx_tr_gastos_viaje
  on public.tr_gastos_viaje(user_id, perfil_id, viaje_id);

create table if not exists public.tr_liquidaciones (
  id            bigint generated by default as identity primary key,
  user_id       text not null,
  perfil_id     bigint,
  chofer_id     bigint references public.tr_choferes(id) on delete set null,
  periodo       text not null default '',
  subtotal      numeric not null default 0,
  iva           numeric not null default 0,
  retencion     numeric not null default 0,
  gastos        numeric not null default 0,
  anticipos     numeric not null default 0,
  total         numeric not null default 0,
  status        text not null default 'borrador',
  notas         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  paid_at       timestamptz,
  constraint tr_liquidaciones_status_check check (status in ('borrador','emitida','pagada','cancelada'))
);

create index if not exists idx_tr_liquidaciones_user_perfil
  on public.tr_liquidaciones(user_id, perfil_id, periodo, status);

create table if not exists public.tr_liquidacion_items (
  id              bigint generated by default as identity primary key,
  user_id         text not null,
  perfil_id       bigint,
  liquidacion_id  bigint not null references public.tr_liquidaciones(id) on delete cascade,
  viaje_id        bigint not null references public.tr_viajes(id) on delete restrict,
  concepto        text not null default 'Flete',
  litros          numeric not null default 0,
  kilos           numeric not null default 0,
  tarifa          numeric not null default 0,
  subtotal        numeric not null default 0,
  iva             numeric not null default 0,
  retencion       numeric not null default 0,
  gastos          numeric not null default 0,
  total           numeric not null default 0,
  metadata        jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  unique (user_id, viaje_id, liquidacion_id)
);

create index if not exists idx_tr_liq_items_viaje
  on public.tr_liquidacion_items(user_id, perfil_id, viaje_id);

create table if not exists public.tr_cliente_contactos (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  perfil_id   bigint,
  cliente_id  bigint references public.tr_clientes(id) on delete cascade,
  nombre      text not null default '',
  email       text not null default '',
  telefono    text not null default '',
  canal       text not null default 'email',
  recibe_documentos boolean not null default true,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

create index if not exists idx_tr_cliente_contactos
  on public.tr_cliente_contactos(user_id, perfil_id, cliente_id);

create table if not exists public.tr_notificaciones (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  perfil_id   bigint,
  viaje_id    bigint references public.tr_viajes(id) on delete cascade,
  canal       text not null default 'manual',
  destinatario text not null default '',
  mensaje     text not null default '',
  status      text not null default 'pendiente',
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  sent_at     timestamptz
);

create index if not exists idx_tr_notificaciones_viaje
  on public.tr_notificaciones(user_id, perfil_id, viaje_id, created_at desc);

create table if not exists public.tr_operador_accesos (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  perfil_id   bigint,
  chofer_id   bigint references public.tr_choferes(id) on delete cascade,
  token_hash  text not null,
  status      text not null default 'activo',
  expires_at  timestamptz,
  last_used_at timestamptz,
  created_at  timestamptz not null default now(),
  unique (user_id, perfil_id, chofer_id, token_hash)
);

create index if not exists idx_tr_operador_accesos_hash
  on public.tr_operador_accesos(token_hash, status);

create table if not exists public.tr_importaciones (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  perfil_id   bigint,
  fuente      text not null default 'excel',
  filename    text not null default '',
  resumen     jsonb not null default '{}'::jsonb,
  status      text not null default 'procesada',
  created_at  timestamptz not null default now()
);

create index if not exists idx_tr_importaciones_user_perfil
  on public.tr_importaciones(user_id, perfil_id, created_at desc);

alter table public.tr_viaje_eventos enable row level security;
alter table public.tr_viaje_documentos enable row level security;
alter table public.tr_tarifas enable row level security;
alter table public.tr_gastos_viaje enable row level security;
alter table public.tr_liquidaciones enable row level security;
alter table public.tr_liquidacion_items enable row level security;
alter table public.tr_cliente_contactos enable row level security;
alter table public.tr_notificaciones enable row level security;
alter table public.tr_operador_accesos enable row level security;
alter table public.tr_importaciones enable row level security;

drop policy if exists tr_viaje_eventos_user_policy on public.tr_viaje_eventos;
create policy tr_viaje_eventos_user_policy on public.tr_viaje_eventos for all using (user_id = auth.uid()::text);

drop policy if exists tr_viaje_documentos_user_policy on public.tr_viaje_documentos;
create policy tr_viaje_documentos_user_policy on public.tr_viaje_documentos for all using (user_id = auth.uid()::text);

drop policy if exists tr_tarifas_user_policy on public.tr_tarifas;
create policy tr_tarifas_user_policy on public.tr_tarifas for all using (user_id = auth.uid()::text);

drop policy if exists tr_gastos_viaje_user_policy on public.tr_gastos_viaje;
create policy tr_gastos_viaje_user_policy on public.tr_gastos_viaje for all using (user_id = auth.uid()::text);

drop policy if exists tr_liquidaciones_user_policy on public.tr_liquidaciones;
create policy tr_liquidaciones_user_policy on public.tr_liquidaciones for all using (user_id = auth.uid()::text);

drop policy if exists tr_liquidacion_items_user_policy on public.tr_liquidacion_items;
create policy tr_liquidacion_items_user_policy on public.tr_liquidacion_items for all using (user_id = auth.uid()::text);

drop policy if exists tr_cliente_contactos_user_policy on public.tr_cliente_contactos;
create policy tr_cliente_contactos_user_policy on public.tr_cliente_contactos for all using (user_id = auth.uid()::text);

drop policy if exists tr_notificaciones_user_policy on public.tr_notificaciones;
create policy tr_notificaciones_user_policy on public.tr_notificaciones for all using (user_id = auth.uid()::text);

drop policy if exists tr_operador_accesos_user_policy on public.tr_operador_accesos;
create policy tr_operador_accesos_user_policy on public.tr_operador_accesos for all using (user_id = auth.uid()::text);

drop policy if exists tr_importaciones_user_policy on public.tr_importaciones;
create policy tr_importaciones_user_policy on public.tr_importaciones for all using (user_id = auth.uid()::text);
