-- GE CONTROL - Transporte operativo inteligente fase 2
-- Capa aditiva: no duplica tr_viajes ni cambia timbrado productivo.

create table if not exists public.tr_proveedores_operacion (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  rfc text not null default '',
  nombre text not null,
  producto_default_id bigint,
  origen_default_id bigint references public.tr_origenes(id) on delete set null,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tr_productos_operacion (
  id bigint generated by default as identity primary key,
  user_id text not null,
  perfil_id bigint,
  nombre text not null,
  clave_producto text not null default '',
  clave_subproducto text not null default '',
  clave_prodserv_cfdi text not null default '',
  unidad text not null default 'LTR',
  densidad_kg_l numeric not null default 0.75,
  material_peligroso boolean not null default true,
  cve_material_peligroso text not null default '',
  embalaje text not null default '4H2',
  permiso_requerido text not null default '',
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.tr_clientes
  add column if not exists destino_default_id bigint references public.tr_destinos(id) on delete set null,
  add column if not exists ruta_default_id bigint references public.tr_rutas(id) on delete set null,
  add column if not exists producto_default_id bigint references public.tr_productos_operacion(id) on delete set null;

alter table if exists public.tr_rutas
  add column if not exists origen_id bigint references public.tr_origenes(id) on delete set null,
  add column if not exists destino_id bigint references public.tr_destinos(id) on delete set null,
  add column if not exists tipo_camino text not null default '',
  add column if not exists tarifa_base numeric not null default 0,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table if exists public.tr_choferes
  add column if not exists vehiculo_frecuente_id bigint references public.tr_vehiculos(id) on delete set null,
  add column if not exists comision_default numeric not null default 0,
  add column if not exists foto_url text not null default '',
  add column if not exists licencia_pdf_url text not null default '',
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table if exists public.tr_viajes
  add column if not exists programa_fecha date,
  add column if not exists programa_semana text not null default '',
  add column if not exists proveedor_id bigint references public.tr_proveedores_operacion(id) on delete set null,
  add column if not exists origen_id bigint references public.tr_origenes(id) on delete set null,
  add column if not exists destino_id bigint references public.tr_destinos(id) on delete set null,
  add column if not exists producto_operacion_id bigint references public.tr_productos_operacion(id) on delete set null,
  add column if not exists tarifa_id bigint references public.tr_tarifas(id) on delete set null,
  add column if not exists subtotal_flete numeric not null default 0,
  add column if not exists comision_operador numeric not null default 0,
  add column if not exists override_tarifa boolean not null default false,
  add column if not exists override_reason text not null default '',
  add column if not exists defaults_json jsonb not null default '{}'::jsonb;

alter table if exists public.tr_liquidaciones
  add column if not exists pago_nomina numeric not null default 0,
  add column if not exists pago_banco numeric not null default 0,
  add column if not exists diferencia_efectivo numeric not null default 0;

alter table if exists public.tr_vehiculo_seguros
  add column if not exists aseguradora_medio_ambiente text not null default '',
  add column if not exists poliza_medio_ambiente text not null default '';

create index if not exists idx_tr_proveedores_operacion_scope
  on public.tr_proveedores_operacion(user_id, perfil_id, activo);
create index if not exists idx_tr_proveedores_operacion_rfc
  on public.tr_proveedores_operacion(user_id, perfil_id, rfc);
create index if not exists idx_tr_productos_operacion_scope
  on public.tr_productos_operacion(user_id, perfil_id, activo);
create index if not exists idx_tr_viajes_programa
  on public.tr_viajes(user_id, perfil_id, programa_fecha, status);
create index if not exists idx_tr_viajes_operativos
  on public.tr_viajes(user_id, perfil_id, proveedor_id, origen_id, destino_id, producto_operacion_id);

alter table public.tr_proveedores_operacion enable row level security;
alter table public.tr_productos_operacion enable row level security;

drop policy if exists tr_proveedores_operacion_user_policy on public.tr_proveedores_operacion;
create policy tr_proveedores_operacion_user_policy
  on public.tr_proveedores_operacion for all
  using (user_id = auth.uid()::text)
  with check (user_id = auth.uid()::text);

drop policy if exists tr_productos_operacion_user_policy on public.tr_productos_operacion;
create policy tr_productos_operacion_user_policy
  on public.tr_productos_operacion for all
  using (user_id = auth.uid()::text)
  with check (user_id = auth.uid()::text);

comment on table public.tr_proveedores_operacion is
  'Proveedores operativos/SAT para inferir origen y producto antes de SAT Sync real.';
comment on table public.tr_productos_operacion is
  'Productos operativos configurables: claves SAT, densidad, material peligroso y permisos requeridos.';
comment on column public.tr_viajes.defaults_json is
  'Snapshot de defaults operativos aplicados al viaje: proveedor/origen/destino/ruta/tarifa/vehiculo/remolques/seguros/permisos.';
